package com.employee.security;

public enum Permission {
    CREATE_USER,
    ASSIGN_ROLE,
    ADD_EMPLOYEE,
    UPDATE_EMPLOYEE,
    UPDATE_NAME_BY_ID,
    DELETE_EMPLOYEE,
    FETCH_EMPLOYEE,
    FETCH_EMPLOYEE_BY_ID,
    FETCH_EMPLOYEE_BY_NAME,
    FETCH_EMPLOYEE_BY_SALARY,
    FETCH_DELETED_EMPLOYEES,
    UPDATE_SELF_PROFILE,
    UPDATE_SELF_PASSWORD,
    RESET_PASSWORD
}
