package com.employee.security;

public enum Permission {
    CREATE_USER,
    ASSIGN_ROLE,
    ADD_EMPLOYEE,
    UPDATE_EMPLOYEE,
    DELETE_EMPLOYEE,
    FETCH_EMPLOYEE,
    FETCH_EMPLOYEEBYNAME,
    FETCH_EMPLOYEEBYSALARY,
    UPDATE_SELF_PROFILE,
    UPDATE_SELF_PASSWORD,
    RESET_PASSWORD
}
